# Lecture 7 examples -- random forest trees

In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier as DNN
from sklearn.model_selection import cross_val_score as cv
from sklearn.datasets import load_breast_cancer
from sklearn.ensemble import RandomForestClassifier as RFC
from time import time
import datetime

In [2]:
data = load_breast_cancer()
X = data.data
y = data.target

In [3]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [5]:
dnn = DNN(hidden_layer_sizes=(200,),random_state=420)

cv(dnn,X,y,cv=5).mean()

0.9349945660611707

In [6]:
dnn.fit(X,y).predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,

In [7]:
dnn.fit(X,y).predict_proba(X)

array([[1.00000000e+00, 5.80211596e-25],
       [1.00000000e+00, 1.00641444e-14],
       [9.99999999e-01, 6.28745603e-10],
       ...,
       [9.99497591e-01, 5.02409394e-04],
       [1.00000000e+00, 2.79983276e-11],
       [1.45552433e-01, 8.54447567e-01]])

In [8]:
times = time()
dnn = DNN(hidden_layer_sizes=(200,),random_state=420)
print(cv(dnn,X,y,cv=5).mean())
print(time() - times)

0.9349945660611707
6.018283367156982


In [9]:
times = time()
clf_rfc = RFC(n_estimators=200,random_state=420)
print(cv(clf_rfc,X,y,cv=5).mean())
print(time() - times)

0.9613414066138798
2.4914846420288086


In [10]:
times = time()
dnn = DNN(hidden_layer_sizes=(50,),random_state=420)
print(cv(dnn,X,y,cv=5).mean())
print(time() - times)

0.934979040521658
7.027089595794678


In [11]:
times = time()
dnn = DNN(hidden_layer_sizes=(50,50),random_state=420)
print(cv(dnn,X,y,cv=5).mean())
print(time() - times)

0.9367179009470579
6.434905767440796


In [12]:
times = time()
dnn = DNN(hidden_layer_sizes=(50,100),random_state=420)
print(cv(dnn,X,y,cv=5).mean())
print(time() - times)

0.9103089582362986
6.187391996383667


In [13]:
times = time()
dnn = DNN(hidden_layer_sizes=(100,100,100),random_state=420)
print(cv(dnn,X,y,cv=5).mean())
print(time() - times)

0.9086166744294365
5.2025721073150635


In [18]:
from sklearn.preprocessing import StandardScaler as SS
X_ = SS().fit_transform(X)
times = time()
dnn = DNN(hidden_layer_sizes=(200,50),random_state=420)
print(cv(dnn,X_,y,cv=5).mean())
print(time() - times)

0.9806862288464524
17.46208620071411


In [24]:
for activef in ["identity","logistic","tanh","relu"]:
    times = time()
    dnn = DNN(hidden_layer_sizes=(200,50),
                activation = activef,
                max_iter = 2000,
                random_state=420)
    print(activef, cv(dnn,X_,y,cv=5).mean())
    print(time() - times)

identity 0.9613724576929048
10.117655038833618
logistic 0.9666356155876418
34.93250131607056
tanh 0.9754385964912281
23.948522806167603
relu 0.9806862288464524
10.301084518432617


In [25]:
dnn.fit(X,y).out_activation_

'logistic'